choice/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('question/', include('question.urls')),
]

question/urls.py
from django.urls import path, include
from . import views
app_name = 'question'
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('<int:id>/', views.detail, name="detail"),
    path('<int:id>/delete/', views.delete, name="delete"),
    path('<int:id>/update1/', views.update1, name="update1"),
    path('<int:id>/update2/', views.update2, name="update2"),

    path('<int:id>/edit/', views.edit, name="edit"),

    path('<int:question_id>/answers/', views.answer_create, name="answer_create"),
    path('<int:question_id>/answers/<int:answer_id>/delete', views.answer_delete, name="answer_delete"),

    path('random/', views.random, name="random"),

    path('search/', views.search, name="search")

]

question/models.py
from django.db import models

# Create your models here.

class Qu(models.Model):
    title = models.CharField(max_length=150)
    choice1 = models.CharField(max_length=150)
    choice2 = models.CharField(max_length=150)
    p1 = models.IntegerField()
    p2 = models.IntegerField()
    image_url1 = models.CharField(max_length=200)
    image_url2 = models.CharField(max_length=200)

class An(models.Model):
    content = models.CharField(max_length=100)
    question = models.ForeignKey(Qu, on_delete=models.CASCADE)

question/views.py
from django.shortcuts import render, redirect
from .models import Qu, An
import random as rand
# Create your views here.
def index(request):
    questions = Qu.objects.all()
    context = {
        'questions': questions
    }
    return render(request, 'index.html', context)

def create(request):
    if request.method == "POST":
        title = request.POST.get("title")
        choice1 = request.POST.get("choice1")
        choice2 = request.POST.get("choice2")
        image_url1 = request.POST.get("image_url1")
        image_url2 = request.POST.get("image_url2")
        Qu.objects.create(
            title = title,
            choice1 = choice1,
            choice2 = choice2,
            p1 = 0,
            p2 = 0,
            image_url1 = image_url1,
            image_url2 = image_url2,
        )
        return redirect('question:index')

    else:
        return render(request, 'form.html')

def detail(request, id):
    question = Qu.objects.get(id=id)
    context = {
        "question" : question
    }
    return render(request, "detail.html", context)

def delete(request, id):
    question = Qu.objects.get(id=id)
    question.delete()
    return redirect('question:index')

def update1(request, id):
    question = Qu.objects.get(id=id)
    print(question.p1)
    question.p1 += 1
    question.save()
    return redirect('question:detail', id)

def update2(request, id):
    question = Qu.objects.get(id=id)
    question.p2 += 1
    question.save()
    return redirect('question:detail', id)

def edit(request, id):
    question = Qu.objects.get(id=id)
    if request.method == "POST": 
        question.title = request.POST.get("title")
        question.choice1 = request.POST.get("choice1")
        question.choice2 = request.POST.get("choice2")
        question.image_url1 = request.POST.get("image_url1")
        question.image_url2 = request.POST.get("image_url2")
        question.save()

        return redirect('question:detail', id)
    else:
        context = {
            'question': question
        }
        return render(request, 'form.html', context)

def answer_create(request, question_id):
    if request.method == "POST":
        content = request.POST.get('content')
        question = Qu.objects.get(id=question_id)

        An.objects.create(content=content, question=question)

        return redirect('question:detail', question_id)
    else:
        pass

def answer_delete(request, question_id, answer_id):
    answer = An.objects.get(id=answer_id)
    answer.delete()
    return redirect('question:detail', question_id)

def random(request):
    questions=Qu.objects.all()
    R = []
    for question in questions:
        R.append(question.id)
    res = rand.choice(R)
    return redirect('question:detail', res)

def search(request):    
    S = request.GET.get('search')
    questions=Qu.objects.all()
    context={
        "S" : S,
        "questions":questions
    }
    return render(request, 'search.html', context)

question/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Q&A</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="icon" href="{% static 'quest.png' %}">
  <link href="https://fonts.googleapis.com/css?family=Yeon+Sung&display=swap" rel="stylesheet">
  <style>
    div {
      font-family: 'Yeon Sung', cursive;
    }
  </style>
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'question:index' %}"> <img src="https://www.stickpng.com/assets/images/5a461301d099a2ad03f9c990.png" style="height:2rem" alt=""> Either</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'question:create' %}">NEW <span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href='{% url "question:random" %}'>random</a>
      <form action="{% url 'question:search'%}" class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      </div>
    </div>
  </div>
</nav>
<body>
  <div class="container">
  {% block body %}
  {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

question/templates/detail.html
{% extends 'base.html' %}
{% block body %}
  <div class="jumbotron">
    <h1 class="display-4">{{question.title}}</h1>
    <hr class="my-4">
    <form action="" method="post">
      {% csrf_token %}
    <a href="{% url 'question:update1' question.id %}" class="btn btn-outline-primary btn-lg btn-block"><img src="{{question.image_url1}}" class="rounded mx-auto d-block" style="height: 15rem;" alt="">{{question.choice1}} : {{question.p1}}</a>
    </form>
    <form action="" method="post">
    {% csrf_token %}
    <a href="{% url 'question:update2' question.id %}" class="btn btn-outline-danger btn-lg btn-block my-3">{{question.choice2}} : {{question.p2}}<img src="{{question.image_url2}}" class="rounded mx-auto d-block" style="height: 15rem;" alt=""></a>
    </form>

    <hr class="my-4">
    <div class="row">
      <div class="col-11">
        <a href="{% url 'question:edit' question.id %}" class="btn btn-outline-dark">edit</a>
        <a href="{% url 'question:delete' question.id %}" class="btn btn-outline-dark">delete</a>
      </div>
      <div class="col-1">
        <a href="{% url 'question:random' %}" class="btn btn-danger">Next</a>
      </div>
    </div>
    <hr class="my-4">
    <form action="{% url 'question:answer_create' question.id %}" method="post">
      {% csrf_token %}
      <div class="container">
        <div class="row">
          <input class="form-control col-10" type="text" name="content">
          <input class="btn btn-dark col-2" type="submit">
        </div>
      </div>
    </form>
    {% if question.an_set.all %}
      {% for answer in question.an_set.all %}
        <div class="alert alert-light m-2 row" role="alert">
            <p class="col-10 mr-4">{{answer.content}}</p>
            <a class="btn btn-outline-secondary btn-xs " href="{% url 'question:answer_delete' question.id answer.id %}">삭제</a>
        </div>
      {% endfor %}
    {% else %}
      <div class="alert alert-secondary my-3" role="alert">
          <p>댓글이 없습니다.</p> 
      </div>
    {% endif %}
  </div>

{% endblock %}

question/templates/form.html
{% extends 'base.html' %}
{% block body %}
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="title">Title</label>
      <input type="text" class="form-control" id="title" name="title" value="{{question.title}}">
    </div>
    <div class="form-group">
      <label for="choice1">Choice1</label>
      <input type="text" class="form-control" id="choice1" name="choice1" value="{{question.choice1}}">
    </div>
    <div class="form-group">
      <label for="image_url1">image_url1</label>
      <input type="text" class="form-control" id="image_url1" name="image_url1" value="{{question.image_url1}}">
    </div>
    <div class="form-group">
      <label for="choice2">Choice2</label>
      <input type="text" class="form-control" id="choice2" name="choice2" value="{{question.choice2}}">
    </div>
    <div class="form-group">
      <label for="image_url2">image_url2</label>
      <input type="text" class="form-control" id="image_url2" name="image_url2" value="{{question.image_url2}}">
    </div>       
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

question/templates/index.html
{% extends 'base.html' %}
{% block body %}
  {% for question in questions %}
  <div class="alert alert-secondary" role="alert">
      {{question.title}} <a href="{% url 'question:detail' question.id %}" class="alert-link">detail</a>
  </div>
  {% endfor %}
{% endblock %}

question/templates/search.html
{% extends 'base.html' %}
{% block body %}
  {% for question in questions %}
    {% if S in question.title or S in question.choice1 or S in question.choice2%}
      <div class="alert alert-secondary" role="alert">
          {{question.title}} <a href="{% url 'question:detail' question.id %}" class="alert-link">detail</a>
      </div>
    {% endif %}
  {% endfor %}
{% endblock %}

question/templates/start.html
{% extends 'base.html' %}
{% block body %}
  {% for question in questions %}
  <div class="alert alert-secondary" role="alert">
      {{question.title}} <a href="{% url 'question:detail' question.id %}" class="alert-link">detail</a>
  </div>
  {% endfor %}
{% endblock %}